# action.yml
name: 'Copybara'
description: 'Transform and move code between repositories'
inputs:
  GITHUB:
    description: 'Source GITHUB URL address'
    required: true
  CONFIG:  
    description: 'Allows you to specify a path to a config file'
    required: false
    default: 'copy.bara.sky'
  SUBCOMMAND:  
    description: 'Allows you to change the command run'
    required: false
    default: 'migrate'
  OPTIONS:
    description: 'Allows you to change the command run'
    required: false
    default: ''
  WORKFLOW:
    description: 'Allows you to specify the workflow to run'
    required: false
    default: 'default'
  SOURCEREF:
    description: 'Allows you to specify the sourceref'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB }}
    - ${{ inputs.CONFIG }}
    - ${{ inputs.SUBCOMMAND }}
    - ${{ inputs.OPTIONS }}
    - ${{ inputs.WORKFLOW }}
    - ${{ inputs.SOURCEREF }}